Repository sigp/anchor, pull requests merged in 2025-07, with the labels that each got.

#379 Reduce memory usage in validator
  anchor/client/src/lib.rs
  anchor/fuzz/fuzz_targets/setup.rs
  anchor/message_sender/src/network.rs
  anchor/message_validator/src/consensus_message.rs
  anchor/message_validator/src/duty_state.rs
  anchor/message_validator/src/lib.rs
  anchor/message_validator/src/message_counts.rs
Labels: ready-for-review, validation, optimization, ready-for-merge

#408 Adjust documentation for `v0.2.0`
  .github/wordlist.txt
  book/src/SUMMARY.md
  book/src/advanced.md
  book/src/advanced_networking.md
  book/src/cli.md
  book/src/running_node.md
  book/src/setup.md
  docs/architecture.md
Labels: documentation, v0.2.0, ready-for-merge

#395 Use the correct role and encoding for sync committee contributions
  anchor/common/ssv_types/src/consensus.rs
  anchor/validator_store/src/lib.rs
Labels: ready-for-review, v0.2.0, ready-for-merge

#415 recursive clone for submodules
  .github/workflows/test-suite.yml
Labels: devops, ready-for-merge

#414 Switch to Go-SSV default ports
  anchor/client/src/cli.rs
  anchor/client/src/config.rs
  anchor/network/src/config.rs
  book/src/advanced_networking.md
  book/src/cli.md
Labels: ready-for-merge

#412 Also allow comma separated CLI values
  anchor/client/src/cli.rs
Labels: bug, cli, ready-for-merge

#421 Remove `fuzz`
  Cargo.lock
  Cargo.toml
  anchor/fuzz/.gitignore
  anchor/fuzz/Cargo.toml
  anchor/fuzz/fuzz_targets/custom_ssz.rs
  anchor/fuzz/fuzz_targets/qbft_target.rs
  anchor/fuzz/fuzz_targets/receive_target.rs
  anchor/fuzz/fuzz_targets/setup.rs
  anchor/fuzz/fuzz_targets/validate_target.rs
Labels: ready-for-merge

#404 Use Go-SSV key formats, convert legacy keys
  Cargo.lock
  anchor/client/src/cli.rs
  anchor/client/src/config.rs
  anchor/client/src/key.rs
  anchor/client/src/lib.rs
  anchor/common/operator_key/src/encrypted.rs
  anchor/keygen/Cargo.toml
  anchor/keygen/src/encryption.rs
  anchor/keygen/src/lib.rs
Labels: ready-for-review, cryptography, cli, v0.2.0, ready-for-merge

#406 Set topic parameters
  Cargo.lock
  Cargo.toml
  anchor/client/Cargo.toml
  anchor/client/src/cli.rs
  anchor/client/src/config.rs
  anchor/client/src/lib.rs
  anchor/message_sender/Cargo.toml
  anchor/message_sender/src/impostor.rs
  anchor/message_sender/src/network.rs
  anchor/network/Cargo.toml
  anchor/network/src/behaviour.rs
  anchor/network/src/config.rs
  anchor/network/src/discovery.rs
  anchor/network/src/handshake/node_info.rs
  anchor/network/src/lib.rs
  anchor/network/src/network.rs
  anchor/network/src/peer_manager.rs
  anchor/network/src/scoring/mod.rs
  anchor/network/src/scoring/topic_score_config.rs
  anchor/subnet_service/Cargo.toml
  anchor/subnet_service/src/lib.rs
  anchor/subnet_service/src/message_rate.rs
  anchor/subnet_tracker/src/lib.rs
Labels: network, v0.2.0, ready-for-merge

#363 Avoid accidentally skipping blocks when switching to live sync
  anchor/eth/src/sync.rs
Labels: database, ready-for-merge

#372 refactor: Revamp startup sequence and check sync status
  Cargo.lock
  Cargo.toml
  anchor/client/src/lib.rs
  anchor/client/src/notifier.rs
  anchor/database/Cargo.toml
  anchor/database/src/lib.rs
  anchor/eth/src/sync.rs
  anchor/message_sender/Cargo.toml
  anchor/message_sender/src/lib.rs
  anchor/message_sender/src/network.rs
  anchor/qbft_manager/Cargo.toml
  anchor/qbft_manager/src/lib.rs
  anchor/qbft_manager/src/tests.rs
  anchor/signature_collector/Cargo.toml
  anchor/signature_collector/src/lib.rs
  anchor/validator_store/src/lib.rs
Labels: ready-for-merge

#434 fix: Avoid duplicate entries in `MultiIndexMap`
  anchor/database/src/multi_index.rs
Labels: bug, database, ready-for-merge

#435 refactor: Switch to let-chains where possible
  Dockerfile
  Dockerfile.devnet
  anchor/Cargo.toml
  anchor/common/qbft/src/lib.rs
  anchor/common/qbft/src/msg_container.rs
  anchor/database/src/state.rs
  anchor/http_metrics/src/lib.rs
  anchor/logging/src/tracing_libp2p_discv5_layer.rs
  anchor/message_sender/src/network.rs
  anchor/network/src/network.rs
  anchor/processor/src/lib.rs
  anchor/signature_collector/src/lib.rs
  anchor/validator_store/src/lib.rs
Labels: ready-for-merge

#447 chore!: Remove legacy key support
  Cargo.lock
  anchor/client/src/cli.rs
  anchor/client/src/key.rs
  anchor/common/operator_key/Cargo.toml
  anchor/common/operator_key/src/legacy.rs
  anchor/common/operator_key/src/lib.rs
  anchor/common/operator_key/test_keys/encrypted_legacy_anchor.txt
  anchor/keygen/README.md
Labels: ready-for-merge

#453 ci: Fix rust version in docker workflow
  .github/workflows/docker.yml
Labels: ready-for-merge

#449 refactor(keysplit): Use `eth2_keystore` from LH instead of reimplementing it
  Cargo.lock
  anchor/keysplit/Cargo.toml
  anchor/keysplit/src/crypto.rs
  anchor/keysplit/src/error.rs
  anchor/keysplit/src/keystore.rs
  anchor/keysplit/src/lib.rs
  anchor/keysplit/src/output.rs
  anchor/keysplit/src/util.rs
Labels: ready-for-merge
