Repository sigp/anchor, pull requests merged in 2025-05, with the labels that each got.

#285 Node fallback endpoints
  Cargo.lock
  anchor/client/src/cli.rs
  anchor/client/src/config.rs
  anchor/client/src/lib.rs
  anchor/eth/Cargo.toml
  anchor/eth/src/sync.rs
Labels: enhancement, ready-for-review, execution layer

#297 Log Count metrics
  Cargo.lock
  anchor/Cargo.toml
  anchor/logging/Cargo.toml
  anchor/logging/src/count_layer.rs
  anchor/logging/src/lib.rs
  anchor/message_validator/src/consensus_message.rs
  anchor/src/main.rs
Labels: ready-for-review, metrics

#294 Avoid stalled sync when fetching highly concentrated logs
  anchor/eth/src/sync.rs
Labels: ready-for-review

#299 Anchor CLI and Quickstart book docs
  .github/wordlist.txt
  book/src/SUMMARY.md
  book/src/cli.md
  book/src/running_node.md
Labels: documentation, ready-for-review

#301 message_validator: fix previous epoch duty count calculation
  anchor/message_validator/src/consensus_state.rs
Labels: bug, validation

#232 Fuzzing via libfuzzer
  Cargo.lock
  Cargo.toml
  anchor/common/qbft/Cargo.toml
  anchor/common/ssv_types/Cargo.toml
  anchor/common/ssv_types/src/consensus.rs
  anchor/common/ssv_types/src/message.rs
  anchor/common/ssv_types/src/msgid.rs
  anchor/common/ssv_types/src/operator.rs
  anchor/common/ssv_types/src/partial_sig.rs
  anchor/fuzz/.gitignore
  anchor/fuzz/Cargo.toml
  anchor/fuzz/fuzz_targets/custom_ssz.rs
  anchor/fuzz/fuzz_targets/qbft_target.rs
  anchor/fuzz/fuzz_targets/receive_target.rs
  anchor/fuzz/fuzz_targets/setup.rs
  anchor/fuzz/fuzz_targets/validate_target.rs
Labels: ready-for-review, major task, fuzzing

#312 Logfile colouring fix
  anchor/logging/src/logging.rs
  anchor/src/main.rs
Labels: ready-for-review, logging

#328 Fix last duty per epoch validation
  anchor/message_validator/src/consensus_message.rs
  anchor/message_validator/src/consensus_state.rs
Labels: bug, validation

#306 Voluntary exit msg validation
  Cargo.lock
  Cargo.toml
  anchor/client/Cargo.toml
  anchor/client/src/lib.rs
  anchor/duties_tracker/Cargo.toml
  anchor/duties_tracker/src/duties_tracker.rs
  anchor/duties_tracker/src/lib.rs
  anchor/duties_tracker/src/voluntary_exit_tracker.rs
  anchor/eth/Cargo.toml
  anchor/eth/src/event_processor.rs
  anchor/eth/src/lib.rs
  anchor/eth/src/sync.rs
  anchor/eth/src/voluntary_exit_processor.rs
  anchor/fuzz/fuzz_targets/setup.rs
  anchor/message_validator/Cargo.toml
  anchor/message_validator/src/consensus_message.rs
  anchor/message_validator/src/lib.rs
  anchor/voluntary_exit/src/lib.rs
Labels: validation

#337 Fix signer state update
  anchor/message_validator/src/consensus_message.rs
  anchor/message_validator/src/consensus_state.rs
  anchor/message_validator/src/lib.rs
  anchor/message_validator/src/message_counts.rs
Labels: bug, ready-for-review, validation

#342 Update LH and semver-compat deps
  Cargo.lock
  Cargo.toml
  anchor/validator_store/Cargo.toml
  anchor/validator_store/src/lib.rs
Labels: ready-for-review, chore, v0.1.0

#298 Networking metrics
  Cargo.lock
  anchor/client/src/lib.rs
  anchor/http_metrics/Cargo.toml
  anchor/http_metrics/src/lib.rs
  anchor/network/src/lib.rs
  anchor/network/src/network.rs
  anchor/network/src/peer_manager.rs
Labels: metrics, v0.1.0

#336 Validate Partial Signature Message by Duty Logic
  anchor/client/src/lib.rs
  anchor/fuzz/fuzz_targets/setup.rs
  anchor/message_validator/src/consensus_message.rs
  anchor/message_validator/src/duty_state.rs
  anchor/message_validator/src/lib.rs
  anchor/message_validator/src/message_counts.rs
  anchor/message_validator/src/partial_signature.rs
Labels: validation, v0.1.0

#352 Set default hardcoded network to Hoodi
  anchor/client/src/config.rs
Labels: cli, v0.1.0

#343 Properly record `validator_store` errors in metrics
  anchor/validator_store/src/lib.rs
  anchor/validator_store/src/metrics.rs
Labels: v0.1.0

#350 Disable mainnet support
  anchor/client/src/cli.rs
  anchor/client/src/lib.rs
  anchor/eth/README.md
  anchor/keysplit/README.md
  anchor/keysplit/src/cli.rs
  anchor/keysplit/src/split.rs
Labels: v0.1.0

#305 Logging improvements
  Cargo.lock
  anchor/client/src/lib.rs
  anchor/common/qbft/Cargo.toml
  anchor/common/qbft/src/lib.rs
  anchor/common/qbft/src/qbft_types.rs
  anchor/common/qbft/src/tests.rs
  anchor/common/ssv_types/src/consensus.rs
  anchor/common/ssv_types/src/message.rs
  anchor/duties_tracker/src/duties_tracker.rs
  anchor/eth/src/event_processor.rs
  anchor/eth/src/sync.rs
  anchor/logging/src/utils.rs
  anchor/message_receiver/Cargo.toml
  anchor/message_receiver/src/manager.rs
  anchor/message_sender/src/network.rs
  anchor/message_validator/src/consensus_message.rs
  anchor/message_validator/src/lib.rs
  anchor/message_validator/src/partial_signature.rs
  anchor/qbft_manager/src/instance.rs
  anchor/qbft_manager/src/lib.rs
  anchor/signature_collector/src/lib.rs
  anchor/validator_store/src/lib.rs
Labels: logging, v0.1.0
