Repository sigp/anchor, pull requests merged in 2025-09, with the labels that each got.

#537 fix: commit validation
  anchor/common/qbft/src/lib.rs
Labels: QBFT, ready-for-merge

#554 feat: reduce validator operation logging noise with aggregated summaries
  .claude/agents/logging-subagent.md
  CLAUDE.md
  anchor/eth/src/event_processor.rs
Labels: logging, ready-for-merge

#528 fix: Validation for prepared round changes before insertion
  anchor/common/qbft/src/lib.rs
  anchor/common/qbft/src/tests.rs
Labels: ready-for-review, QBFT, ready-for-merge, v1.0.0

#523 fix: Remove error log for missing operators
  anchor/eth/src/event_processor.rs
  anchor/eth/src/util.rs
Labels: ready-for-merge, v1.0.0

#566 fix: use proposal hash if not justified
  anchor/common/qbft/src/lib.rs
Labels: ready-for-merge

#571 fix(qbft): Check round change quorum disregarding root
  anchor/common/qbft/src/lib.rs
  anchor/common/qbft/src/msg_container.rs
Labels: ready-for-review, QBFT, ready-for-merge

#570 fix: fix name and docs of `lowest_partial_quorum_above_round`
  anchor/common/qbft/src/lib.rs
  anchor/common/qbft/src/msg_container.rs
Labels: ready-for-merge

#522 fix: Do not log exit event as unknown during historic sync
  anchor/common/ssv_types/src/cluster.rs
  anchor/eth/src/event_processor.rs
Labels: ready-for-merge, v1.0.0

#577 feat: specific qbft errors
  anchor/common/qbft/src/error.rs
  anchor/common/qbft/src/lib.rs
  anchor/common/qbft/src/tests.rs
  anchor/qbft_manager/src/instance.rs
Labels: QBFT, ready-for-merge

#588 fix: remove state check for changing rounds
  anchor/common/qbft/src/lib.rs
Labels: ready-for-review, QBFT, ready-for-merge, v1.0.0

#594 fix(qbft): check whether the justification signer is in the committee
  anchor/common/qbft/src/lib.rs
Labels: ready-for-review, QBFT, ready-for-merge, v1.0.0

#606 fix: Check all quorums more rigorously
  anchor/common/qbft/src/lib.rs
  anchor/common/qbft/src/msg_container.rs
  anchor/common/qbft/src/qbft_types.rs
Labels: ready-for-review, QBFT, ready-for-merge, v1.0.0

#598 fix(qbft): prevent unsafe leader fallback when highest prepared data missing
  anchor/common/qbft/src/lib.rs
  anchor/common/qbft/src/tests.rs
  anchor/common/ssv_types/src/message.rs
Labels: QBFT, ready-for-merge, v1.0.0

#607 fix(qbft): store data from decided message
  anchor/common/qbft/src/lib.rs
Labels: QBFT, ready-for-merge, v1.0.0

#609 fix: safe arithmetic in timeout calculation
  anchor/common/qbft/src/lib.rs
  anchor/qbft_manager/src/instance.rs
  anchor/qbft_manager/src/timeout.rs
Labels: ready-for-merge, v1.0.0

#612 chore: Increase `MAX_VALIDATORS_PER_OPERATOR` to 3000
  anchor/validator_store/src/lib.rs
Labels: ready-for-review, ready-for-merge, v1.0.0

#617 feat: Add CLI flag to disable Enr auto update
  anchor/client/src/cli.rs
  anchor/client/src/config.rs
  anchor/network/src/config.rs
  anchor/network/src/discovery.rs
Labels: ready-for-merge, v1.0.0

#619 feat: Add logging flags for dependencies
  anchor/logging/src/logging.rs
  anchor/src/main.rs
Labels: logging, ready-for-merge, v1.0.0

#608 fix!: Removed operators in committee
  anchor/database/src/operator_operations.rs
  anchor/database/src/schema.rs
  anchor/database/src/sql_operations.rs
  anchor/database/src/table_schema.sql
  anchor/database/src/tests/metadata_tests.rs
  anchor/database/src/tests/utils.rs
  anchor/message_validator/src/consensus_message.rs
  anchor/message_validator/src/lib.rs
  anchor/message_validator/src/partial_signature.rs
Labels: ready-for-merge, v1.0.0

#621 chore: Release v1.0.0-rc.0
  Cargo.lock
  anchor/Cargo.toml
  anchor/client/Cargo.toml
  anchor/common/version/src/lib.rs
  anchor/keygen/Cargo.toml
  anchor/keysplit/Cargo.toml
Labels: ready-for-merge, trivial

#622 chore: Backmerge release v1.0.0
  .github/mergify.yml
  Cargo.lock
  Cargo.toml
  anchor/Cargo.toml
  anchor/client/Cargo.toml
  anchor/client/src/cli.rs
  anchor/client/src/config.rs
  anchor/client/src/lib.rs
  anchor/common/global_config/src/data_dir.rs
  anchor/common/qbft/src/lib.rs
  anchor/common/qbft/src/msg_container.rs
  anchor/common/qbft/src/qbft_types.rs
  anchor/common/qbft/src/tests.rs
  anchor/common/ssv_types/src/cluster.rs
  anchor/common/ssv_types/src/message.rs
  anchor/common/ssv_types/src/round.rs
  anchor/common/version/src/lib.rs
  anchor/database/src/operator_operations.rs
  anchor/database/src/schema.rs
  anchor/database/src/sql_operations.rs
  anchor/database/src/table_schema.sql
  anchor/database/src/tests/metadata_tests.rs
  anchor/database/src/tests/utils.rs
  anchor/eth/src/event_processor.rs
  anchor/keygen/Cargo.toml
  anchor/keysplit/Cargo.toml
  anchor/logging/src/logging.rs
  anchor/logging/src/tracing_libp2p_discv5_layer.rs
  anchor/message_validator/src/consensus_message.rs
  anchor/message_validator/src/lib.rs
  anchor/message_validator/src/partial_signature.rs
  anchor/network/src/config.rs
  anchor/network/src/discovery.rs
  anchor/network/src/handshake/envelope/mod.rs
  anchor/qbft_manager/src/instance.rs
  anchor/qbft_manager/src/timeout.rs
  anchor/src/main.rs
  anchor/validator_store/src/lib.rs
Labels: ready-for-review, do-not-merge

#580 feat: ssz infrastructure
  Cargo.lock
  Cargo.toml
  anchor/common/qbft/Cargo.toml
  anchor/common/qbft/src/error.rs
  anchor/common/qbft/src/lib.rs
  anchor/common/qbft/src/qbft_types.rs
  anchor/common/qbft/src/tests.rs
  anchor/common/ssv_types/Cargo.toml
  anchor/common/ssv_types/src/consensus.rs
  anchor/common/ssv_types/src/lib.rs
  anchor/common/ssv_types/src/message.rs
  anchor/common/ssv_types/src/msgid.rs
  anchor/common/ssv_types/src/operator.rs
  anchor/common/ssv_types/src/partial_sig.rs
  anchor/common/ssv_types/src/test_utils.rs
  anchor/message_sender/Cargo.toml
  anchor/message_sender/src/lib.rs
  anchor/message_sender/src/network.rs
  anchor/message_sender/src/testing.rs
  anchor/message_validator/Cargo.toml
  anchor/message_validator/src/consensus_message.rs
  anchor/message_validator/src/duty_state.rs
  anchor/message_validator/src/lib.rs
  anchor/message_validator/src/partial_signature.rs
  anchor/network/Cargo.toml
  anchor/signature_collector/src/lib.rs
  anchor/validator_store/src/lib.rs
Labels: enhancement, ready-for-merge

#626 test: add SSV event processing integration tests
  Cargo.lock
  anchor/database/Cargo.toml
  anchor/database/src/lib.rs
  anchor/database/src/tests/cluster_tests.rs
  anchor/database/src/tests/metadata_tests.rs
  anchor/database/src/tests/mod.rs
  anchor/database/src/tests/operator_tests.rs
  anchor/database/src/tests/state_tests.rs
  anchor/database/src/tests/utils.rs
  anchor/database/src/tests/validator_tests.rs
  anchor/eth/Cargo.toml
  anchor/eth/src/lib.rs
  anchor/eth/tests/integration.rs
Labels: testing, ready-for-merge

#633 test: add comprehensive operator lifecycle integration test
  Cargo.lock
  anchor/database/src/operator_operations.rs
  anchor/database/src/sql_operations.rs
  anchor/eth/Cargo.toml
  anchor/eth/src/lib.rs
  anchor/eth/tests/common/mod.rs
  anchor/eth/tests/integration.rs
  anchor/eth/tests/operator_lifecycle.rs
Labels: testing, ready-for-merge
