Repository sigp/anchor, pull requests merged in 2025-06, with the labels that each got.

#354 Increase default logfile parameters
  anchor/logging/src/logging.rs
  book/src/cli.md
Labels: v0.1.0

#345 Prepare release CI
  .github/workflows/docker.yml
  .github/workflows/release.yml
  Makefile
  anchor/Cargo.toml
Labels: ready-for-review, devops, v0.1.0

#356 Do not warn if a validator is removed before index is set
  anchor/database/src/validator_operations.rs
Labels: ready-for-review, logging

#360 Delete unused `network_actions` module
  anchor/eth/src/lib.rs
  anchor/eth/src/network_actions.rs
Labels: chore

#338 Add mergify config
  .github/mergify.yml
  .github/scripts/check_success_job.sh
  .github/workflows/test-suite.yml
Labels: devops, chore

#368 Add peer score params and thresholds
  anchor/client/src/cli.rs
  anchor/client/src/config.rs
  anchor/network/src/behaviour.rs
  anchor/network/src/lib.rs
  anchor/network/src/network.rs
  anchor/network/src/peer_score_config.rs
Labels: network

#383 Fix permissions of check_success_job.sh
  .github/scripts/check_success_job.sh
Labels: devops, ready-for-merge, trivial

#361 Avoid unnecessary allocations and conversions in database
  anchor/common/ssv_types/src/operator.rs
  anchor/common/ssv_types/src/util.rs
  anchor/database/src/cluster_operations.rs
  anchor/database/src/operator_operations.rs
  anchor/database/src/tests/cluster_tests.rs
  anchor/database/src/tests/state_tests.rs
  anchor/database/src/tests/utils.rs
  anchor/eth/src/event_processor.rs
  anchor/eth/src/sync.rs
  anchor/eth/src/util.rs
  anchor/keysplit/src/cli.rs
Labels: database, ready-for-merge

#378 Return references instead of cloning in `MultiIndexMap`
  Cargo.toml
  anchor/database/src/cluster_operations.rs
  anchor/database/src/multi_index.rs
  anchor/database/src/state.rs
  anchor/database/src/tests/state_tests.rs
  anchor/database/src/tests/utils.rs
  anchor/database/src/validator_operations.rs
  anchor/eth/src/event_processor.rs
  anchor/message_receiver/src/manager.rs
  anchor/validator_store/src/lib.rs
Labels: database, optimization, ready-for-merge

#364 Reduce logging during sync
  anchor/eth/src/event_processor.rs
  anchor/eth/src/util.rs
Labels: database, logging, ready-for-merge

#393 Create scoring mod
  anchor/network/src/behaviour.rs
  anchor/network/src/lib.rs
  anchor/network/src/scoring/mod.rs
  anchor/network/src/scoring/peer_score_config.rs
Labels: ready-for-merge

#397 Merge immediately if branch is up to date and passes tests
  .github/mergify.yml
Labels: devops, ready-for-merge, waiting-on-author

#398 Correctly use the workspace edition everywhere
  anchor/common/bls_lagrange/Cargo.toml
  anchor/common/bls_lagrange/src/blsful.rs
  anchor/common/bls_lagrange/src/blst.rs
  anchor/common/bls_lagrange/src/lib.rs
  anchor/common/version/Cargo.toml
  anchor/fuzz/Cargo.toml
  anchor/fuzz/fuzz_targets/qbft_target.rs
  anchor/fuzz/fuzz_targets/receive_target.rs
  anchor/fuzz/fuzz_targets/setup.rs
  anchor/http_metrics/Cargo.toml
  anchor/http_metrics/src/lib.rs
Labels: ready-for-review, chore
