Repository sigp/anchor, pull requests merged in 2025-10, with the labels that each got.

#597 chore: switch to unstable lighthouse and update dependencies
  Cargo.lock
  Cargo.toml
  anchor/common/ssv_types/src/consensus.rs
Labels: ready-for-review, chore, ready-for-merge

#654 chore: Fix libp2p metrics feature
  .gitignore
  anchor/network/Cargo.toml
Labels: ready-for-review, chore, ready-for-merge, trivial

#650 fix: implement periodic peer discovery without connection failure tracking
  anchor/logging/src/tracing_libp2p_discv5_layer.rs
  anchor/network/src/discovery.rs
  anchor/network/src/handshake/mod.rs
  anchor/network/src/network.rs
  anchor/network/src/peer_manager/connection.rs
  anchor/network/src/peer_manager/discovery.rs
  anchor/network/src/peer_manager/mod.rs
Labels: bug, network, ready-for-merge, v1.0.0

#661 fix: Allow incomming peers
  anchor/network/src/peer_manager/connection.rs
Labels: ready-for-merge, v1.0.0

#648 chore: Update libp2p for v1.0.0 branch
  Cargo.lock
  Cargo.toml
Labels: ready-for-merge, v1.0.0, queued

#655 feat: Logging improvement
  Cargo.lock
  anchor/logging/Cargo.toml
  anchor/logging/src/count_layer.rs
  anchor/logging/src/format.rs
  anchor/logging/src/lib.rs
  anchor/logging/src/utils.rs
  anchor/message_validator/src/lib.rs
  anchor/network/src/discovery.rs
  anchor/network/src/network.rs
  anchor/src/main.rs
Labels: ready-for-merge, v1.0.0

#662 fix: Prevent dialing connected peers
  anchor/network/src/peer_manager/connection.rs
Labels: ready-for-merge, v1.0.0, queued
