Repository sigp/anchor, pull requests merged in 2025-03, with the labels that each got.

#159 Message sending for Signature Collector
  Cargo.lock
  anchor/client/src/lib.rs
  anchor/network/src/network.rs
  anchor/signature_collector/Cargo.toml
  anchor/signature_collector/src/lib.rs
  anchor/validator_store/Cargo.toml
  anchor/validator_store/src/lib.rs
Labels: ready-for-review, network

#152 Create message_validator crate
  Cargo.lock
  Cargo.toml
  anchor/client/Cargo.toml
  anchor/client/src/lib.rs
  anchor/message_sender/src/lib.rs
  anchor/message_validator/Cargo.toml
  anchor/message_validator/src/lib.rs
  anchor/network/Cargo.toml
  anchor/network/src/network.rs
  anchor/processor/Cargo.toml
  anchor/processor/src/lib.rs
  anchor/qbft_manager/src/lib.rs
  anchor/signature_collector/src/lib.rs
Labels: ready-for-review, validation

#170 Switch back to official `blst` release and revisit zeroing keys
  Cargo.lock
  Cargo.toml
  anchor/common/bls_lagrange/src/blsful.rs
  anchor/common/bls_lagrange/src/blst.rs
  anchor/common/bls_lagrange/src/lib.rs
Labels: ready-for-review, cryptography

#158 Peer manager heartbeat
  Cargo.lock
  anchor/network/Cargo.toml
  anchor/network/src/network.rs
  anchor/network/src/peer_manager.rs
Labels: ready-for-review, network

#160 SignedSSVMessage and SSVMessage validation
  Cargo.lock
  anchor/common/qbft/src/lib.rs
  anchor/common/qbft/src/qbft_types.rs
  anchor/common/qbft/src/tests.rs
  anchor/common/ssv_types/Cargo.toml
  anchor/common/ssv_types/src/lib.rs
  anchor/common/ssv_types/src/message.rs
  anchor/common/ssv_types/src/msgid.rs
  anchor/common/ssv_types/src/share.rs
  anchor/common/ssv_types/src/sql_conversions.rs
  anchor/database/src/tests/utils.rs
  anchor/eth/src/util.rs
  anchor/message_sender/src/testing.rs
  anchor/network/Cargo.toml
  anchor/network/src/network.rs
  anchor/qbft_manager/src/tests.rs
  anchor/signature_collector/src/lib.rs
Labels: ready-for-review, validation

#166 Properly handle messages sent by ourselves
  anchor/common/qbft/src/lib.rs
  anchor/common/qbft/src/qbft_types.rs
  anchor/common/qbft/src/tests.rs
  anchor/message_sender/src/lib.rs
  anchor/message_sender/src/network.rs
  anchor/message_sender/src/testing.rs
  anchor/qbft_manager/src/lib.rs
  anchor/signature_collector/src/lib.rs
Labels: ready-for-review, QBFT

#169 Add ENR-related logging
  anchor/network/src/discovery.rs
Labels: ready-for-review, network

#167 Embed message id into outgoing qbft messages
  anchor/client/src/lib.rs
  anchor/common/qbft/src/lib.rs
  anchor/common/qbft/src/tests.rs
  anchor/qbft_manager/src/lib.rs
  anchor/qbft_manager/src/tests.rs
Labels: ready-for-review, QBFT

#172 Add pre-commit hook for formatting, linting, and sorting
  .githooks/pre-commit
Labels: ready-for-review, chore

#150 Keysplitter
  Cargo.lock
  Cargo.toml
  anchor/Cargo.toml
  anchor/client/src/cli.rs
  anchor/client/src/config.rs
  anchor/client/src/lib.rs
  anchor/common/ssv_types/src/lib.rs
  anchor/database/Cargo.toml
  anchor/database/src/keysplit_operations.rs
  anchor/database/src/lib.rs
  anchor/database/src/sql_operations.rs
  anchor/eth/src/event_processor.rs
  anchor/eth/src/sync.rs
  anchor/eth/src/util.rs
  anchor/keysplit/Cargo.toml
  anchor/keysplit/src/cli.rs
  anchor/keysplit/src/crypto.rs
  anchor/keysplit/src/error.rs
  anchor/keysplit/src/keystore.rs
  anchor/keysplit/src/lib.rs
  anchor/keysplit/src/output.rs
  anchor/keysplit/src/split.rs
  anchor/keysplit/src/util.rs
  anchor/src/main.rs
Labels: enhancement, ready-for-review, nice-to-have

#168 Handle validated messages
  Cargo.lock
  Cargo.toml
  anchor/client/Cargo.toml
  anchor/client/src/lib.rs
  anchor/database/Cargo.toml
  anchor/message_receiver/Cargo.toml
  anchor/message_receiver/src/lib.rs
  anchor/message_receiver/src/manager.rs
  anchor/message_receiver/src/testing.rs
  anchor/message_validator/src/lib.rs
  anchor/network/Cargo.toml
  anchor/network/src/network.rs
  anchor/qbft_manager/src/lib.rs
  anchor/qbft_manager/src/tests.rs
Labels: network, QBFT

#171 Stateless QBFT consensus message semantic validation
  Cargo.lock
  anchor/client/src/lib.rs
  anchor/common/qbft/src/lib.rs
  anchor/common/ssv_types/src/consensus.rs
  anchor/common/ssv_types/src/lib.rs
  anchor/database/src/cluster_operations.rs
  anchor/database/src/lib.rs
  anchor/database/src/multi_index.rs
  anchor/database/src/state.rs
  anchor/message_validator/Cargo.toml
  anchor/message_validator/src/lib.rs
Labels: ready-for-review, validation

#192 Fix decoding QbftMessage
  anchor/common/qbft/src/lib.rs
  anchor/common/ssv_types/src/consensus.rs
  anchor/common/ssv_types/src/msgid.rs
  anchor/message_validator/src/lib.rs
Labels: bug, ready-for-review, network

#184 Rsa keygen
  Cargo.lock
  Cargo.toml
  anchor/Cargo.toml
  anchor/client/Cargo.toml
  anchor/client/src/lib.rs
  anchor/keygen/Cargo.toml
  anchor/keygen/src/lib.rs
  anchor/keysplit/src/util.rs
  anchor/src/main.rs
Labels: enhancement, ready-for-review

#186 Update deps
  Cargo.lock
  Cargo.toml
  Makefile
  anchor/common/bls_lagrange/Cargo.toml
  anchor/common/bls_lagrange/src/blst.rs
  anchor/common/bls_lagrange/src/lib.rs
  anchor/database/src/tests/utils.rs
  anchor/message_receiver/Cargo.toml
  anchor/message_receiver/src/lib.rs
  anchor/message_receiver/src/manager.rs
  anchor/message_receiver/src/testing.rs
  anchor/message_validator/Cargo.toml
  anchor/message_validator/src/lib.rs
  anchor/network/Cargo.toml
  anchor/network/src/behaviour.rs
  anchor/network/src/discovery.rs
  anchor/network/src/handshake/mod.rs
  anchor/network/src/network.rs
  anchor/network/src/peer_manager.rs
  anchor/processor/tests/processor_tests.rs
  anchor/qbft_manager/src/tests.rs
  anchor/src/environment.rs
Labels: ready-for-review

#185 Remove traits and refactor tests
  Cargo.lock
  anchor/client/src/lib.rs
  anchor/common/qbft/src/lib.rs
  anchor/common/ssv_types/src/committee.rs
  anchor/common/ssv_types/src/consensus.rs
  anchor/common/ssv_types/src/lib.rs
  anchor/common/ssv_types/src/msgid.rs
  anchor/common/ssv_types/src/partial_sig.rs
  anchor/database/src/lib.rs
  anchor/database/src/state.rs
  anchor/message_receiver/Cargo.toml
  anchor/message_receiver/src/lib.rs
  anchor/message_receiver/src/manager.rs
  anchor/message_receiver/src/testing.rs
  anchor/message_validator/src/consensus_message.rs
  anchor/message_validator/src/lib.rs
  anchor/network/Cargo.toml
  anchor/network/src/network.rs
Labels: ready-for-review, validation, chore

#203 network: disable libp2p message signing
  anchor/network/src/network.rs
Labels: network

#189 Rust Dependency Caching
  .github/workflows/test-suite.yml
  Makefile
Labels: chore

#204 Change `validation_mode` to `Permissive` and `MessageAuthenticity` to `RandomAuthor`
  anchor/network/src/network.rs
Labels: ready-for-review, network

#196 Rsa private key file encryption
  Cargo.lock
  Cargo.toml
  anchor/client/src/cli.rs
  anchor/client/src/config.rs
  anchor/client/src/lib.rs
  anchor/keygen/Cargo.toml
  anchor/keygen/src/encryption.rs
  anchor/keygen/src/lib.rs
  anchor/keysplit/Cargo.toml
  anchor/src/main.rs
Labels: enhancement, ready-for-review, nice-to-have

#191 Validate qbft logic
  Cargo.lock
  anchor/client/src/lib.rs
  anchor/common/qbft/src/config.rs
  anchor/common/qbft/src/lib.rs
  anchor/common/qbft/src/qbft_types.rs
  anchor/common/ssv_types/src/committee.rs
  anchor/common/ssv_types/src/lib.rs
  anchor/common/ssv_types/src/msgid.rs
  anchor/common/ssv_types/src/round.rs
  anchor/message_receiver/Cargo.toml
  anchor/message_receiver/src/lib.rs
  anchor/message_receiver/src/manager.rs
  anchor/message_receiver/src/testing.rs
  anchor/message_sender/Cargo.toml
  anchor/message_sender/src/network.rs
  anchor/message_validator/Cargo.toml
  anchor/message_validator/src/consensus_message.rs
  anchor/message_validator/src/consensus_state.rs
  anchor/message_validator/src/lib.rs
  anchor/message_validator/src/message_counts.rs
  anchor/network/Cargo.toml
  anchor/network/src/discovery.rs
  anchor/network/src/network.rs
Labels: validation
