Repository sigp/anchor, pull requests merged in 2025-08, with the labels that each got.

#459 refactor(network): Avoid specialized Lighthouse types
  Cargo.lock
  Cargo.toml
  anchor/network/Cargo.toml
  anchor/network/src/config.rs
  anchor/network/src/discovery.rs
  anchor/network/src/network.rs
Labels: network, ready-for-merge

#458 refactor: Remove pre-genesis polling
  anchor/client/src/lib.rs
Labels: ready-for-merge, v0.3.0

#456 feat: prune peers lowest score peers
  anchor/network/src/network.rs
  anchor/network/src/peer_manager/mod.rs
Labels: ready-for-merge, v0.3.0

#448 refactor: Implement data dir module for central management of paths
  Cargo.lock
  anchor/client/src/config.rs
  anchor/client/src/key.rs
  anchor/client/src/lib.rs
  anchor/common/global_config/Cargo.toml
  anchor/common/global_config/src/data_dir.rs
  anchor/common/global_config/src/lib.rs
  anchor/keygen/Cargo.toml
  anchor/keygen/src/lib.rs
  anchor/network/Cargo.toml
  anchor/network/src/config.rs
  anchor/network/src/discovery.rs
  anchor/network/src/keypair_utils.rs
  anchor/network/src/network.rs
  anchor/src/main.rs
Labels: ready-for-merge, v0.3.0

#470 chore: Clippy for 1.89
  anchor/eth/src/util.rs
  anchor/message_validator/src/lib.rs
  anchor/validator_store/src/lib.rs
Labels: ready-for-review, ready-for-merge

#387 feat(database): Add `metadata` table for upgradability and avoiding database switchups
  Cargo.lock
  anchor/client/src/lib.rs
  anchor/common/ssv_types/src/domain_type.rs
  anchor/database/src/lib.rs
  anchor/database/src/schema.rs
  anchor/database/src/sql_operations.rs
  anchor/database/src/table_schema.sql
  anchor/database/src/tests/metadata_tests.rs
  anchor/database/src/tests/mod.rs
  anchor/database/src/tests/state_tests.rs
  anchor/database/src/tests/utils.rs
  anchor/keysplit/Cargo.toml
  anchor/keysplit/src/split.rs
  anchor/network/src/discovery.rs
  anchor/network/src/network.rs
  anchor/src/main.rs
Labels: database, ready-for-merge, v0.3.0

#452 chore: Update dependencies
  Cargo.lock
  Cargo.toml
  anchor/client/Cargo.toml
  anchor/client/src/config.rs
  anchor/client/src/lib.rs
  anchor/eth/src/event_parser.rs
  anchor/eth/src/sync.rs
  anchor/eth/src/util.rs
  anchor/http_metrics/Cargo.toml
  anchor/http_metrics/src/lib.rs
  anchor/network/Cargo.toml
  anchor/network/src/behaviour.rs
  anchor/network/src/config.rs
  anchor/network/src/discovery.rs
  anchor/network/src/handshake/mod.rs
  anchor/network/src/lib.rs
  anchor/network/src/metrics.rs
  anchor/network/src/peer_manager/connection.rs
  anchor/network/src/peer_manager/discovery.rs
  anchor/network/src/peer_manager/types.rs
Labels: ready-for-merge, v0.3.0

#476 fix: Revert `multi_index_map` refactor
  Cargo.lock
  anchor/database/Cargo.toml
  anchor/database/src/cluster_operations.rs
  anchor/database/src/lib.rs
  anchor/database/src/multi_index.rs
  anchor/database/src/state.rs
  anchor/database/src/tests/mod.rs
  anchor/database/src/tests/state_tests.rs
  anchor/database/src/tests/utils.rs
  anchor/database/src/validator_operations.rs
  anchor/eth/src/event_processor.rs
  anchor/eth/src/index_sync.rs
  anchor/http_api/src/router.rs
  anchor/message_receiver/src/manager.rs
  anchor/subnet_service/src/lib.rs
  anchor/validator_store/src/lib.rs
Labels: ready-for-merge

#477 fix: revert removal of `base_hash`
  anchor/signature_collector/src/lib.rs
  anchor/validator_store/src/lib.rs
Labels: ready-for-merge

#485 chore: `cargo update` to fix CI
  Cargo.lock
Labels: ready-for-merge, v0.3.0

#484 chore: small git chore
  .githooks/pre-commit
  .gitignore
Labels: chore, ready-for-merge

#475 feat: Add lockfile to data dir
  .github/workflows/docker.yml
  Cargo.lock
  Dockerfile
  Dockerfile.devnet
  anchor/Cargo.toml
  anchor/common/global_config/Cargo.toml
  anchor/common/global_config/src/data_dir.rs
  anchor/common/global_config/src/lib.rs
  anchor/src/main.rs
Labels: ready-for-merge, v0.3.0

#430 ci: Add CI checks for conventional commits
  .github/workflows/pr-checks.yml
  .github/workflows/test-suite.yml
Labels: ready-for-review, devops

#495 ci: Remove x86 Apple from the release builds
  .github/workflows/release.yml
  docs/docs/pages/index.mdx
Labels: ready-for-merge

#499 fix: Do not log duplicate errors, instead of only
  anchor/network/src/network.rs
Labels: ready-for-merge, v0.3.0

#504 fix: Only historic sync using a synced endpoint
  anchor/eth/src/sync.rs
Labels: ready-for-merge, v0.3.0

#500 fix: Pass in slot metadata to avoid errors on late collection start
  anchor/validator_store/src/lib.rs
Labels: bug, ready-for-review, ready-for-merge, v0.3.0

#513 fix: Do not punish peers during sync
  anchor/client/src/lib.rs
  anchor/message_receiver/src/manager.rs
Labels: bug, ready-for-merge, v0.3.1

#512 docs: small revision to the documentation
  CONTRIBUTING.md
  README.md
  docs/docs/pages/cli-keygen.mdx
  docs/docs/pages/cli-node.mdx
  docs/docs/pages/development_environment.mdx
  docs/docs/pages/installation.mdx
  docs/docs/pages/introduction.mdx
  docs/docs/pages/metrics.mdx
  docs/docs/pages/running_an_operator.mdx
  docs/docs/pages/what_is_ssv.mdx
  docs/vocs.config.ts
  metrics/README.md
Labels: documentation, ready-for-merge

#511 chore: Release v0.3.1
  Cargo.lock
  anchor/Cargo.toml
  anchor/client/Cargo.toml
  anchor/common/version/src/lib.rs
  anchor/keygen/Cargo.toml
  anchor/keysplit/Cargo.toml
Labels: ready-for-review, v0.3.1

#520 chore: Add PartialEq and Eq to KeyId
  anchor/common/bls_lagrange/src/blsful.rs
  anchor/common/bls_lagrange/src/blst.rs
Labels: ready-for-merge, trivial

#527 fix: Allow reaching consensus in PREPARE state
  anchor/common/qbft/src/lib.rs
Labels: QBFT, ready-for-merge, v1.0.0

#534 feat: future round validation
  anchor/common/qbft/src/lib.rs
Labels: QBFT, ready-for-merge

#545 chore: add Claude Code specialized agents configuration
  .claude/agents/code-reviewer-subagent.md
  .claude/agents/qbft-subagent.md
  .gitignore
Labels: ready-for-merge

#550 docs: update CLAUDE.md with tester-subagent configuration
  .claude/agents/tester-subagent.md
  .github/wordlist.txt
  CLAUDE.md
Labels: ready-for-merge

#544 fix: prepare justification fetching
  anchor/common/qbft/src/lib.rs
Labels: ready-for-merge
