Repository sigp/anchor, pull requests merged in 2025-04, with the labels that each got.

#219 Only complain about missing aggregated commit if the instance completed successfully
  anchor/qbft_manager/src/lib.rs
Labels: bug, ready-for-review, QBFT, logging

#214 Address BLST audit
  anchor/common/bls_lagrange/Cargo.toml
  anchor/common/bls_lagrange/src/blsful.rs
  anchor/common/bls_lagrange/src/blst.rs
  anchor/common/bls_lagrange/src/lib.rs
Labels: ready-for-review, cryptography

#215 Signature verification
  Cargo.lock
  anchor/message_validator/Cargo.toml
  anchor/message_validator/src/consensus_message.rs
  anchor/message_validator/src/consensus_state.rs
  anchor/message_validator/src/lib.rs
  anchor/message_validator/src/partial_signature.rs
Labels: ready-for-review, validation

#230 Switch to unbounded queue
  anchor/eth/src/event_processor.rs
  anchor/eth/src/index_sync.rs
Labels: bug, ready-for-review

#238 Remove unused deps
  Cargo.lock
  Cargo.toml
  anchor/Cargo.toml
  anchor/eth/Cargo.toml
  anchor/http_api/Cargo.toml
  anchor/keysplit/Cargo.toml
  anchor/message_validator/Cargo.toml
  anchor/network/Cargo.toml
  anchor/qbft_manager/Cargo.toml
  anchor/validator_store/Cargo.toml
Labels: chore

#235 Keygen documentation
  .github/wordlist.txt
  anchor/keygen/README.md
Labels: documentation, ready-for-review

#237 Remove validation expect
  anchor/common/qbft/src/lib.rs
Labels: ready-for-review, QBFT

#236 Keysplitter documentation
  .github/wordlist.txt
  anchor/keysplit/README.md
Labels: documentation, ready-for-review

#233 Redundant qbft checks
  anchor/common/qbft/src/lib.rs
Labels: ready-for-review, QBFT

#274 Fix deadlock in message validator
  anchor/message_validator/src/lib.rs
Labels: bug, ready-for-review

#190 Impostor Anchor
  anchor/client/src/cli.rs
  anchor/client/src/config.rs
  anchor/client/src/lib.rs
  anchor/database/src/lib.rs
  anchor/database/src/operator_operations.rs
  anchor/database/src/state.rs
  anchor/message_sender/src/impostor.rs
  anchor/message_sender/src/lib.rs
  anchor/qbft_manager/src/lib.rs
  anchor/qbft_manager/src/tests.rs
  anchor/signature_collector/src/lib.rs
  anchor/validator_store/src/lib.rs
Labels: ready-for-review

#273 add validators endpoint
  Cargo.lock
  anchor/client/src/lib.rs
  anchor/common/api_types/src/lib.rs
  anchor/http_api/Cargo.toml
  anchor/http_api/src/lib.rs
  anchor/http_api/src/router.rs
Labels: ready-for-review

#283 Enable aarch64 builds
  .github/workflows/docker.yml
Labels: ready-for-review

#281 setup mev-boost support
  anchor/client/src/cli.rs
  anchor/client/src/config.rs
  anchor/client/src/lib.rs
  anchor/validator_store/src/lib.rs
Labels: enhancement, ready-for-review

#275 Committees endpoint
  anchor/common/api_types/src/lib.rs
  anchor/http_api/src/router.rs
Labels: ready-for-review

#284 Fix flipped condition for committee relevancy check
  anchor/message_receiver/src/manager.rs
Labels: bug, ready-for-review

#286 Node version in metadata
  anchor/network/src/network.rs
Labels: enhancement, ready-for-review

#282 Health endpoint
  Cargo.lock
  anchor/http_api/Cargo.toml
  anchor/http_api/src/router.rs
Labels: ready-for-review

#280 Handle liquidated/reactivated clusters and update fee recipient
  anchor/common/ssv_types/src/cluster.rs
  anchor/validator_store/src/lib.rs
Labels: bug, ready-for-review

#288 Fix index uniqueness for cluster owners
  anchor/database/src/lib.rs
  anchor/database/src/validator_operations.rs
Labels: bug, ready-for-review

#228 Duty logic validation for consensus messages
  Cargo.lock
  anchor/client/src/lib.rs
  anchor/common/ssv_types/src/cluster.rs
  anchor/database/src/state.rs
  anchor/message_receiver/src/manager.rs
  anchor/message_sender/src/network.rs
  anchor/message_validator/Cargo.toml
  anchor/message_validator/src/consensus_message.rs
  anchor/message_validator/src/consensus_state.rs
  anchor/message_validator/src/duties/duties_tracker.rs
  anchor/message_validator/src/duties/mod.rs
  anchor/message_validator/src/lib.rs
  anchor/message_validator/src/partial_signature.rs
Labels: ready-for-review, validation

#296 Small refactoring for event processor
  anchor/eth/src/event_processor.rs
  anchor/eth/src/sync.rs
  anchor/eth/src/util.rs
Labels: chore

#291 Correctly set fee recipient
  anchor/database/src/cluster_operations.rs
  anchor/database/src/sql_operations.rs
  anchor/database/src/table_schema.sql
  anchor/database/src/tests/cluster_tests.rs
  anchor/database/src/tests/utils.rs
  anchor/database/src/validator_operations.rs
  anchor/eth/src/event_processor.rs
Labels: bug, ready-for-review

#290 Execution metrics
  Cargo.lock
  anchor/eth/Cargo.toml
  anchor/eth/src/event_processor.rs
  anchor/eth/src/lib.rs
  anchor/eth/src/metrics.rs
  anchor/eth/src/sync.rs
Labels: ready-for-review, execution layer, metrics

#209 File Logging
  Cargo.lock
  Cargo.toml
  anchor/Cargo.toml
  anchor/client/Cargo.toml
  anchor/client/src/cli.rs
  anchor/client/src/lib.rs
  anchor/logging/Cargo.toml
  anchor/logging/src/lib.rs
  anchor/logging/src/logging.rs
  anchor/logging/src/tracing_libp2p_discv5_layer.rs
  anchor/logging/src/utils.rs
  anchor/message_validator/Cargo.toml
  anchor/src/logging.rs
  anchor/src/main.rs
Labels: ready-for-review
