Repository sigp/anchor, pull requests merged in 2025-01, with the labels that each got.

#85 Move QBFT crate
  Cargo.toml
  anchor/common/qbft/Cargo.toml
  anchor/common/qbft/src/config.rs
  anchor/common/qbft/src/error.rs
  anchor/common/qbft/src/lib.rs
  anchor/common/qbft/src/tests.rs
  anchor/common/qbft/src/types.rs
  anchor/common/qbft/src/validation.rs
Labels: ready-for-review

#76 create signature collector and make processor stateless
  Cargo.lock
  Cargo.toml
  anchor/processor/Cargo.toml
  anchor/processor/src/lib.rs
  anchor/processor/tests/processor_tests.rs
  anchor/signature_collector/Cargo.toml
  anchor/signature_collector/src/lib.rs
Labels: ready-for-review

#59 Execution integration
  .github/wordlist.txt
  .gitignore
  Cargo.lock
  Cargo.toml
  anchor/database/src/cluster_operations.rs
  anchor/database/src/operator_operations.rs
  anchor/database/src/sql_operations.rs
  anchor/database/src/state.rs
  anchor/database/src/tests/state_tests.rs
  anchor/eth/Cargo.toml
  anchor/eth/README.md
  anchor/eth/execution.rs
  anchor/eth/src/error.rs
  anchor/eth/src/event_parser.rs
  anchor/eth/src/event_processor.rs
  anchor/eth/src/gen.rs
  anchor/eth/src/lib.rs
  anchor/eth/src/network_actions.rs
  anchor/eth/src/sync.rs
  anchor/eth/src/util.rs
  anchor/http_api/Cargo.toml
  anchor/network/Cargo.toml
  book/book.toml
Labels: ready-for-review, execution layer

#77 Add QBFT manager
  Cargo.lock
  Cargo.toml
  anchor/common/qbft/Cargo.toml
  anchor/common/qbft/src/config.rs
  anchor/common/qbft/src/error.rs
  anchor/common/qbft/src/lib.rs
  anchor/common/qbft/src/tests.rs
  anchor/common/qbft/src/types.rs
  anchor/common/ssv_types/Cargo.toml
  anchor/common/ssv_types/src/lib.rs
  anchor/common/ssv_types/src/message.rs
  anchor/common/ssv_types/src/msgid.rs
  anchor/network/Cargo.toml
  anchor/network/src/lib.rs
  anchor/processor/src/lib.rs
  anchor/qbft_manager/Cargo.toml
  anchor/qbft_manager/src/lib.rs
Labels: ready-for-review

#73 Duty services
  Cargo.lock
  Cargo.toml
  anchor/Cargo.toml
  anchor/client/Cargo.toml
  anchor/client/src/config.rs
  anchor/client/src/lib.rs
  anchor/common/qbft/src/error.rs
  anchor/common/ssv_types/src/message.rs
  anchor/qbft_manager/src/lib.rs
  anchor/signature_collector/src/lib.rs
  anchor/src/main.rs
  anchor/validator_store/Cargo.toml
  anchor/validator_store/src/lib.rs
  anchor/validator_store/src/sync_committee_service.rs
Labels: ready-for-review

#97 Ensure the "workspace.dependencies" table is sorted
  .github/workflows/test-suite.yml
  Cargo.toml
  Makefile
Labels: ready-for-review, devops

#105 Remove `ssv_types` dependency on `qbft`
  Cargo.lock
  anchor/common/qbft/Cargo.toml
  anchor/common/qbft/src/lib.rs
  anchor/common/ssv_types/Cargo.toml
  anchor/common/ssv_types/src/message.rs
  anchor/qbft_manager/src/lib.rs
Labels: ready-for-review

#79 Subnet search
  Cargo.lock
  anchor/network/Cargo.toml
  anchor/network/src/discovery.rs
  anchor/network/src/network.rs
Labels: ready-for-review

#80 Subscribe to topic and decode SignedSSVMessage
  Cargo.lock
  anchor/network/Cargo.toml
  anchor/network/src/network.rs
  anchor/network/src/types.rs
  anchor/network/src/types/ssv_message.rs
Labels: ready-for-review, network

#94 Qbft tests
  anchor/common/qbft/src/config.rs
  anchor/common/qbft/src/lib.rs
  anchor/common/qbft/src/tests.rs
  anchor/common/qbft/src/types.rs
  book/book.toml
Labels: ready-for-review, QBFT

#83 Add lockbud to CI
  .github/scripts/check_lockbud.sh
  .github/workflows/test-suite.yml
Labels: ready-for-review

#109 wire up everything
  Cargo.lock
  Cargo.toml
  anchor/Cargo.toml
  anchor/client/Cargo.toml
  anchor/client/src/cli.rs
  anchor/client/src/config.rs
  anchor/client/src/lib.rs
  anchor/database/src/lib.rs
  anchor/database/src/operator_operations.rs
  anchor/database/src/state.rs
  anchor/eth/execution.rs
  anchor/eth/src/sync.rs
  anchor/src/environment.rs
  anchor/src/main.rs
  anchor/validator_store/Cargo.toml
  anchor/validator_store/src/lib.rs
Labels: ready-for-review

#95 `blst` lagrange interpolation
  Cargo.lock
  Cargo.toml
  anchor/common/bls_lagrange/Cargo.toml
  anchor/common/bls_lagrange/src/blsful.rs
  anchor/common/bls_lagrange/src/blst.rs
  anchor/common/bls_lagrange/src/lib.rs
  anchor/signature_collector/Cargo.toml
  anchor/signature_collector/src/lib.rs
Labels: ready-for-review, spicy, cryptography
